name: map586
channels:
  - conda-forge
dependencies:
  - xtensor=0.24.0
  - xtensor-python=0.26.0
  - xeus-cling=0.13.0
  - xeus-python=0.13.4
  - opencv=4.5.3
  - cmake=3.21.3
  - cxx-compiler=1.3.0
  - pybind11=2.8.1
  - numpy
  - matplotlib
